export const WEAPON_ATTRIBUTES = [
  {
    id: "pistol",
    label: "Pistola 9mm",
    shortLabel: "Pistola",
    price: 60,
    starterAmmo: 18,
    ammoPack: 24,
    ammoPrice: 18,
    fireInterval: 0.24,
    range: 170,
    hitRadius: 0.9,
    damage: 34,
    automatic: false,
    visualTracerLength: 8.5,
    visualTracerThickness: 0.022,
    visualTracerColor: 0xffefb0,
    visualTracerLife: 0.05,
    spreadBaseRadius: 0.024,
    spreadBloomRadius: 0.034,
    bloomKick: 0.48,
    crosshairPxScale: 560,
    muzzleKick: 1.15,
    recoilReturnSpeed: 5.2,
    poseRecoil: 0.34,
    cameraKick: 0.11,
    cameraLift: 0.05,
    recoilClimb: 0.014,
    hipFireMultiplier: 1,
    aimedSpreadMultiplier: 1,
    scopeFov: null,
    useScopeOverlay: false
  },
  {
    id: "shotgun",
    label: "Escopeta táctica",
    shortLabel: "Escopeta",
    price: 140,
    starterAmmo: 12,
    ammoPack: 16,
    ammoPrice: 28,
    fireInterval: 0.62,
    range: 88,
    hitRadius: 1.6,
    damage: 68,
    automatic: false,
    visualTracerLength: 6.8,
    visualTracerThickness: 0.034,
    visualTracerColor: 0xffd38a,
    visualTracerLife: 0.06,
    spreadBaseRadius: 0.074,
    spreadBloomRadius: 0.074,
    bloomKick: 1.02,
    crosshairPxScale: 500,
    muzzleKick: 1.5,
    recoilReturnSpeed: 3.2,
    poseRecoil: 0.52,
    cameraKick: 0.18,
    cameraLift: 0.095,
    recoilClimb: 0.04,
    hipFireMultiplier: 1,
    aimedSpreadMultiplier: 1,
    scopeFov: null,
    useScopeOverlay: false
  },
  {
    id: "fusil",
    label: "Fusil de asalto",
    shortLabel: "Fusil",
    price: 220,
    starterAmmo: 30,
    ammoPack: 36,
    ammoPrice: 42,
    fireInterval: 0.1,
    range: 240,
    hitRadius: 0.95,
    damage: 24,
    automatic: true,
    visualTracerLength: 10.5,
    visualTracerThickness: 0.018,
    visualTracerColor: 0xfff6cb,
    visualTracerLife: 0.04,
    spreadBaseRadius: 0.022,
    spreadBloomRadius: 0.028,
    bloomKick: 0.34,
    crosshairPxScale: 610,
    muzzleKick: 0.92,
    recoilReturnSpeed: 7.2,
    poseRecoil: 0.24,
    cameraKick: 0.075,
    cameraLift: 0.032,
    recoilClimb: 0.024,
    hipFireMultiplier: 1,
    aimedSpreadMultiplier: 1,
    scopeFov: null,
    useScopeOverlay: false
  },
  {
    id: "francotirador",
    label: "Francotirador",
    shortLabel: "Francotirador",
    price: 360,
    starterAmmo: 10,
    ammoPack: 12,
    ammoPrice: 60,
    fireInterval: 0.92,
    range: 420,
    hitRadius: 0.7,
    damage: 100,
    automatic: false,
    visualTracerLength: 12.5,
    visualTracerThickness: 0.016,
    visualTracerColor: 0xe8f4ff,
    visualTracerLife: 0.08,
    spreadBaseRadius: 0.008,
    spreadBloomRadius: 0.02,
    bloomKick: 0.44,
    crosshairPxScale: 720,
    muzzleKick: 1.4,
    recoilReturnSpeed: 2.6,
    poseRecoil: 0.56,
    cameraKick: 0.16,
    cameraLift: 0.075,
    recoilClimb: 0.055,
    hipFireMultiplier: 9.5,
    aimedSpreadMultiplier: 0.08,
    scopeFov: 22,
    useScopeOverlay: true
  }
];

export const WEAPON_ATTRIBUTES_BY_ID = new Map(
  WEAPON_ATTRIBUTES.map((weapon) => [weapon.id, weapon])
);

export function getWeaponAttributes(weaponId) {
  return WEAPON_ATTRIBUTES_BY_ID.get(weaponId) ?? WEAPON_ATTRIBUTES[0];
}
